export const bikes = [
  {
    id: 1,
    image: "https://imgur.com/rPesUNB.jpeg",
    name: "RAV2R Speed Carbon - 700c Rim - 22 Gears - Shimano 105 Kit - Disc Brake",
    price: 200,
    category: "Performance",
  },
  {
    id: 2,
    image: "https://imgur.com/4vAAHcO.jpeg",
    name: 'Tuff - 25" Rim - 21v - Shimano Gear - Disc Brake - Viking',
    price: 150,
    category: "Leisure",
  },
  {
    id: 3,
    image: "https://imgur.com/uoOmch1.jpeg",
    name: 'GTS Rav bike - 29" Rim - Hydraulic brake - Full Suspension Frame - Shimano XTR RV Gear - Carbon Red',
    price: 250,
    category: "Premium",
  },
  {
    id: 4,
    image: "https://imgur.com/pwFZiTk.jpeg",
    name: 'Fat bike - 26" Rim - 12v - 4.0 Tires - Absolute',
    price: 180,
    category: "Trail",
  },
  {
    id: 5,
    image: "https://imgur.com/P9on9Li.jpeg",
    name: "Speed Road - 700c Rim - KSW - Shimano Group - Claris 2x8V",
    price: 200,
    category: "Performance",
  },
  {
    id: 6,
    image: "https://imgur.com/LWYCKpf.jpeg",
    name: 'Feminine Bike GTS M1 - 26" Rim - Shimano Gear - V-Brake - Retro',
    price: 150,
    category: "Leisure",
  },
  {
    id: 7,
    image: "https://imgur.com/ss01e1d.jpeg",
    name: 'GTS Rav2 bike - 29" Rim - Hydraulic brake - Full Suspension Frame - 1X12 Shimano Deore XT RV - Carbon Red',
    price: 240,
    category: "Premium",
  },
  {
    id: 8,
    image: "https://imgur.com/v318aI4.jpeg",
    name: 'GTS M1 Fat - 26" Rim - Hydraulic Brake - 9v - I-VTEC Fat ',
    price: 190,
    category: "Trail",
  },
];
